#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : pucch1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Mar 17 19:03:06 -0400 2026
# SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: pucch1.sh [-help]
# usage: pucch1.sh [-lib_map_path]
# usage: pucch1.sh [-noclean_files]
# usage: pucch1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'pucch1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xpm xil_defaultlib xbip_utils_v3_0_10 axi_utils_v2_0_6 c_reg_fd_v12_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_6 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_14 c_mux_bit_v12_0_6 c_shift_ram_v12_0_14 xbip_bram18k_v3_0_6 mult_gen_v12_0_16 cmpy_v6_0_18 floating_point_v7_0_17 xfft_v9_1_3 xlconstant_v1_1_6 xlslice_v1_0_2 fifo_generator_v13_2_5 blk_mem_gen_v8_4_4 xbip_dsp48_mult_v3_0_6 xbip_dsp48_multadd_v3_0_6 div_gen_v5_1_16 xlconcat_v2_1_3)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "pucch1.sh - Script generated by export_simulation (Vivado v2019.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xpm $vlogan_opts -sverilog \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/pucch1/ipshared/aca9/demapping.srcs/sources_1/new/demapping.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_demapping_0_1/sim/pucch1_demapping_0_1.v" \
    "$ref_dir/../../../bd/pucch1/ipshared/fcfe/physical_control.srcs/sources_1/new/physical_control.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_physical_control_0_0/sim/pucch1_physical_control_0_0.v" \
    "$ref_dir/../../../bd/pucch1/ipshared/5e8b/frame_sync.srcs/sources_1/new/frame_sync.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_frame_sync_0_0/sim/pucch1_frame_sync_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/xfft_0/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/xfft_0/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/xfft_0/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/xfft_0/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/xfft_0/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/xfft_0/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/xfft_0/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/xfft_0/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/xfft_0/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/xfft_0/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/xfft_0/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_16 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/xfft_0/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work cmpy_v6_0_18 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/xfft_0/hdl/cmpy_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_0_17 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/xfft_0/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xfft_v9_1_3 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/xfft_0/hdl/xfft_v9_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/xfft_0/sim/xfft_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/ctr_pre_fft_0/ctr_pre_fft.srcs/sources_1/new/ctr_pre_fft.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/ofdm_demodulation.srcs/sources_1/ip/ctr_pre_fft_0/sim/ctr_pre_fft_0.v" \
    "$ref_dir/../../../bd/pucch1/ipshared/d443/ofdm_demodulation.srcs/sources_1/new/fft.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_ofdm_demodulation_0_0/sim/pucch1_ofdm_demodulation_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ipshared/34f7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_xlconstant_0_0/sim/pucch1_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_xlslice_0_0/sim/pucch1_xlslice_0_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_frame_sync_1_0/sim/pucch1_frame_sync_1_0.v" \
    "$ref_dir/../../../bd/pucch1/ipshared/a151/ulcch_parameter.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_ulcch_parameter_0_0/sim/pucch1_ulcch_parameter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_data_dmrs_selection_0_0/data_dmrs_selection.srcs/sources_1/ip/data_dmrs_fifo_1/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_data_dmrs_selection_0_0/data_dmrs_selection.srcs/sources_1/ip/data_dmrs_fifo_1/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_data_dmrs_selection_0_0/data_dmrs_selection.srcs/sources_1/ip/data_dmrs_fifo_1/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_data_dmrs_selection_0_0/data_dmrs_selection.srcs/sources_1/ip/data_dmrs_fifo_1/sim/data_dmrs_fifo_1.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_data_dmrs_selection_0_0/data_dmrs_selection.srcs/sources_1/ip/data_dmrs_fifo_0/sim/data_dmrs_fifo_0.v" \
    "$ref_dir/../../../bd/pucch1/ipshared/0c12/data_dmrs_selection.srcs/sources_1/new/data_dmrs_selection.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_data_dmrs_selection_0_0/sim/pucch1_data_dmrs_selection_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_de_spread_0_0/de_spread.srcs/sources_1/ip/de_spread_cmpy_0/sim/de_spread_cmpy_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_de_spread_0_0/de_spread.srcs/sources_1/ip/de_spread_fifo_0/sim/de_spread_fifo_0.v" \
    "$ref_dir/../../../bd/pucch1/ipshared/b055/de_spread.srcs/sources_1/new/de_spread.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_de_spread_0_0/sim/pucch1_de_spread_0_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_de_spread_1_0/sim/pucch1_de_spread_1_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_n_cs_gen_0_0/sources_1/ip/ncs_gen_fifo/sim/ncs_gen_fifo.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_n_cs_gen_0_0/sources_1/ip/ncs_scra_seq_8/scamble_sequence.srcs/sources_1/new/scramble_sequence.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_n_cs_gen_0_0/sources_1/ip/ncs_scra_seq_8/sim/ncs_scra_seq_8.v" \
    "$ref_dir/../../../bd/pucch1/ipshared/2aa0/sources_1/new/n_cs_gen.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_n_cs_gen_0_0/sim/pucch1_n_cs_gen_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_phase_gen_0_0/phase_gen.srcs/sources_1/ip/modulo_12_1_nomalize/ip/modulo12_mult_gen_1/sim/modulo12_mult_gen_1.vhd" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_phase_gen_0_0/phase_gen.srcs/sources_1/ip/modulo_12_1_nomalize/ip/modulo12_mult_gen_2/sim/modulo12_mult_gen_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_phase_gen_0_0/phase_gen.srcs/sources_1/ip/modulo_12_1_nomalize/new/modulo_12.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_phase_gen_0_0/phase_gen.srcs/sources_1/ip/modulo_12_1_nomalize/sim/modulo_12_1_nomalize.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_phase_gen_0_0/phase_gen.srcs/sources_1/ip/dis_alpha_gen_0/ip/mult_gen_dis_alpha/sim/mult_gen_dis_alpha.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_phase_gen_0_0/phase_gen.srcs/sources_1/ip/dis_alpha_gen_0/new/dis_alpha_gen.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_phase_gen_0_0/phase_gen.srcs/sources_1/ip/dis_alpha_gen_0/sim/dis_alpha_gen_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_phase_gen_0_0/phase_gen.srcs/sources_1/ip/alpha_modulo_12_0/sim/alpha_modulo_12_0.v" \
    "$ref_dir/../../../bd/pucch1/ipshared/ce59/phase_gen.srcs/sources_1/new/phase_gen.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_phase_gen_0_0/sim/pucch1_phase_gen_0_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_phase_gen_control_0_0/phase_gen_control.srcs/sources_1/ip/phase_fifo_0/sim/phase_fifo_0.v" \
    "$ref_dir/../../../bd/pucch1/ipshared/cdc1/phase_gen_control.srcs/sources_1/new/phase_gen_control.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_phase_gen_control_0_0/sim/pucch1_phase_gen_control_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_base_sequence_0_0/base_seq.srcs/sources_1/ip/phi_matrix_0/phi_matrix.srcs/sources_1/ip/blk_mem_gen_0/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_base_sequence_0_0/base_seq.srcs/sources_1/ip/phi_matrix_0/phi_matrix.srcs/sources_1/ip/blk_mem_gen_0/sim/blk_mem_gen_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_base_sequence_0_0/base_seq.srcs/sources_1/ip/phi_matrix_0/phi_matrix.srcs/sources_1/new/phi_matrix.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_base_sequence_0_0/base_seq.srcs/sources_1/ip/phi_matrix_0/sim/phi_matrix_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_base_sequence_0_0/base_seq.srcs/sources_1/ip/modulo_30_2/modulo_n.srcs/sources_1/ip/m30_mul1/sim/m30_mul1.vhd" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_base_sequence_0_0/base_seq.srcs/sources_1/ip/modulo_30_2/modulo_n.srcs/sources_1/ip/m30_mul0/sim/m30_mul0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_base_sequence_0_0/base_seq.srcs/sources_1/ip/modulo_30_2/modulo_n.srcs/sources_1/new/modulo_n.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_base_sequence_0_0/base_seq.srcs/sources_1/ip/modulo_30_2/sim/modulo_30_2.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_base_sequence_0_0/base_seq.srcs/sources_1/ip/scramble_sequence_1bit_0/scamble_sequence.srcs/sources_1/new/scramble_sequence.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_base_sequence_0_0/base_seq.srcs/sources_1/ip/scramble_sequence_1bit_0/sim/scramble_sequence_1bit_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_base_sequence_0_0/base_seq.srcs/sources_1/ip/modulo_30_1/sim/modulo_30_1.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_base_sequence_0_0/base_seq.srcs/sources_1/ip/scramble_sequence_8bits_0/sim/scramble_sequence_8bits_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_base_sequence_0_0/base_seq.srcs/sources_1/ip/modulo_30_0/sim/modulo_30_0.v" \
    "$ref_dir/../../../bd/pucch1/ipshared/85a1/base_seq.srcs/sources_1/new/base_sequence.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_base_sequence_0_0/sim/pucch1_base_sequence_0_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_base_sequence_1_0/sim/pucch1_base_sequence_1_0.v" \
    "$ref_dir/../../../bd/pucch1/ipshared/1390/sources_1/new/nfs_gen.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_nfs_gen_0_0/sim/pucch1_nfs_gen_0_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_ba_seq_control_0_0/ba_seq_control.srcs/sources_1/ip/base_se_control_blk_1/sim/base_se_control_blk_1.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_ba_seq_control_0_0/ba_seq_control.srcs/sources_1/ip/ba_seq_control_blk_0/sim/ba_seq_control_blk_0.v" \
    "$ref_dir/../../../bd/pucch1/ipshared/1353/ba_seq_control.srcs/sources_1/new/ba_seq_control.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_ba_seq_control_0_0/sim/pucch1_ba_seq_control_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_com_mul_cyclic_0_0/sources_1/ip/cyclic_cmpy_0/sim/cyclic_cmpy_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/pucch1/ipshared/7068/sources_1/new/com_mul_cyclic.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_com_mul_cyclic_0_0/sim/pucch1_com_mul_cyclic_0_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_xlconstant_0_1/sim/pucch1_xlconstant_0_1.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_xlconstant_0_2/sim/pucch1_xlconstant_0_2.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_xlconstant_1_0/sim/pucch1_xlconstant_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_uci_dmrs_gen_0_0/sources_1/ip/uci_dmrs_cmpy_0/sim/uci_dmrs_cmpy_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/pucch1/ipshared/67db/sources_1/new/uci_dmrs_gen.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_uci_dmrs_gen_0_0/sim/pucch1_uci_dmrs_gen_0_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_n_cs_gen_0_1/sim/pucch1_n_cs_gen_0_1.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_phase_gen_0_1/sim/pucch1_phase_gen_0_1.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_phase_gen_control_0_1/sim/pucch1_phase_gen_control_0_1.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_base_sequence_0_1/sim/pucch1_base_sequence_0_1.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_base_sequence_1_1/sim/pucch1_base_sequence_1_1.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_nfs_gen_0_1/sim/pucch1_nfs_gen_0_1.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_ba_seq_control_0_1/sim/pucch1_ba_seq_control_0_1.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_com_mul_cyclic_0_1/sim/pucch1_com_mul_cyclic_0_1.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_xlconstant_0_3/sim/pucch1_xlconstant_0_3.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_xlconstant_1_1/sim/pucch1_xlconstant_1_1.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_xlconstant_2_0/sim/pucch1_xlconstant_2_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_wise_spreading_0_0/wise_spreading.srcs/sources_1/ip/wise_rom_7/sim/wise_rom_7.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_wise_spreading_0_0/wise_spreading.srcs/sources_1/ip/wise_rom_6/sim/wise_rom_6.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_wise_spreading_0_0/wise_spreading.srcs/sources_1/ip/wise_rom_5/sim/wise_rom_5.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_wise_spreading_0_0/wise_spreading.srcs/sources_1/ip/wise_rom_4/sim/wise_rom_4.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_wise_spreading_0_0/wise_spreading.srcs/sources_1/ip/wise_rom_3/sim/wise_rom_3.v" \
    "$ref_dir/../../../bd/pucch1/ipshared/63d0/wise_spreading.srcs/sources_1/new/wise_spreading.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_wise_spreading_0_0/sim/pucch1_wise_spreading_0_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_wise_spreading_0_1/sim/pucch1_wise_spreading_0_1.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_dmrs_wise_spreading_0_0/sim/pucch1_dmrs_wise_spreading_0_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_dmrs_wise_spreading_1_0/sim/pucch1_dmrs_wise_spreading_1_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_uci_dmrs_gen_0_1/sim/pucch1_uci_dmrs_gen_0_1.v" \
    "$ref_dir/../../../bd/pucch1/ipshared/fee0/payload_est_SINR.srcs/sources_1/new/payload_est_SINR.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_payload_est_SINR_0_0/sim/pucch1_payload_est_SINR_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_mean_data_0_0/mean_data.srcs/sources_1/ip/c1_cmpy/sim/c1_cmpy.vhd" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_mean_data_0_0/mean_data.srcs/sources_1/ip/mean_data_cmpy_4/sim/mean_data_cmpy_4.vhd" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_mean_data_0_0/mean_data.srcs/sources_1/ip/mean_data_cmpy_3/sim/mean_data_cmpy_3.vhd" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_mean_data_0_0/mean_data.srcs/sources_1/ip/mean_data_cmpy_2/sim/mean_data_cmpy_2.vhd" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_mean_data_0_0/mean_data.srcs/sources_1/ip/mean_data_cmpy_1/sim/mean_data_cmpy_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_mult_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_mean_data_0_0/mean_data.srcs/sources_1/ip/mean_data_div_gen_0/hdl/xbip_dsp48_mult_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_mean_data_0_0/mean_data.srcs/sources_1/ip/mean_data_div_gen_0/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work div_gen_v5_1_16 $vhdlan_opts \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ip/pucch1_mean_data_0_0/mean_data.srcs/sources_1/ip/mean_data_div_gen_0/hdl/div_gen_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_mean_data_0_0/mean_data.srcs/sources_1/ip/mean_data_div_gen_0/sim/mean_data_div_gen_0.vhd" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_mean_data_0_0/mean_data.srcs/sources_1/ip/mean_noise_mult_0/sim/mean_noise_mult_0.vhd" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_mean_data_0_0/mean_data.srcs/sources_1/ip/power_cmpy_0/sim/power_cmpy_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_mean_data_0_0/mean_data.srcs/sources_1/ip/mean_data_fifo0/sim/mean_data_fifo0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_mean_data_0_0/mean_data.srcs/sources_1/ip/sig_power_cmpy_4/sim/sig_power_cmpy_4.vhd" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_mean_data_0_0/mean_data.srcs/sources_1/ip/sig_power_cmpy_3/sim/sig_power_cmpy_3.vhd" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_mean_data_0_0/mean_data.srcs/sources_1/ip/sig_power_cmpy_2/sim/sig_power_cmpy_2.vhd" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_mean_data_0_0/mean_data.srcs/sources_1/ip/sig_power_cmpy_1/sim/sig_power_cmpy_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/pucch1/ipshared/ffc9/mean_data.srcs/sources_1/new/mean_data.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_mean_data_0_0/sim/pucch1_mean_data_0_0.v" \
    "$ref_dir/../../../bd/pucch1/ipshared/d12c/sr_ack_detector.srcs/sources_1/new/sr_ack_detector.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_sr_ack_detector_0_0/sim/pucch1_sr_ack_detector_0_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_xlconstant_0_4/sim/pucch1_xlconstant_0_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_3 $vlogan_opts +v2k \
    "$ref_dir/../../../../pucch1_integration.srcs/sources_1/bd/pucch1/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_xlconcat_0_0/sim/pucch1_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_xlconcat_0_1/sim/pucch1_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/pucch1/ip/pucch1_xlconstant_2_1/sim/pucch1_xlconstant_2_1.v" \
    "$ref_dir/../../../bd/pucch1/sim/pucch1.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.pucch1 xil_defaultlib.glbl -o pucch1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./pucch1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./pucch1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key pucch1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc pucch1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./pucch1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: pucch1.sh [-help]\n\
Usage: pucch1.sh [-lib_map_path]\n\
Usage: pucch1.sh [-reset_run]\n\
Usage: pucch1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
