@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Feb 27 17:21:07 -0500 2026
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim dis_alpha_gen_behav -key {Behavioral:sim_1:Functional:dis_alpha_gen} -tclbatch dis_alpha_gen.tcl -log simulate.log"
call xsim  dis_alpha_gen_behav -key {Behavioral:sim_1:Functional:dis_alpha_gen} -tclbatch dis_alpha_gen.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
